media: public
content:
  - name: posts
    label: Posts
    type: collection
    path: 'content/posts2'
    filename: '{fields.slug}.md'
    view:
      fields: [ title, published, date ]
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
      - name: date
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
      - name: slug
        label: Slug
        type: string
  - name: layers
    label: Layers
    type: collection
    path: 'content/layers'
    filename: '{slug}.json'
    format: json
    fields:
      - name: slug
        type: string
      - name: display_name
        type: string
      - name: source
        type: string
  - name: layerfile
    label: Layer File
    type: file
    path: 'content/layers.json'
    format: json
    fields:
      - name: layers
        type: object
        fields:
          - name: name
            label: Name
            type: string
          - name: source
            label: Source
            type: string
        list: true